# Generated by Django 5.2.6 on 2026-06-19 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('classic', 'Classic Professional'), ('modern', 'Modern Creative'), ('minimal', 'Clean Minimal'), ('tech', 'Tech / Dev'), ('academic', 'Academic Style'), ('creative', 'Creative'), ('executive', 'Executive'), ('compact', 'Compact')], default='classic', max_length=20)),
                ('color_scheme', models.CharField(default='blue', max_length=20)),
                ('show_photo', models.BooleanField(default=False)),
                ('show_skills_bar', models.BooleanField(default=True)),
                ('show_projects', models.BooleanField(default=True)),
                ('show_certifications', models.BooleanField(default=True)),
                ('font_style', models.CharField(default='inter', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_template', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
